name: weekly_bible_trivia
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_thunk: ^0.4.0

  get_it: ^7.2.0
  shared_preferences: ^2.0.9
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.2.0
  cloud_firestore: ^3.1.5
  redux_logging: ^0.5.0
  i18n_extension: ^4.1.3
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0
  sqflite: ^2.0.1
  path_provider: ^2.0.8
  dio: ^4.0.4
  expandable: ^5.0.1
  curved_navigation_bar: ^1.0.1
  ntp: ^2.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
    - family: Verdana
      fonts:
        - asset: assets/fonts/Verdana-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-ThinItalic.ttf
          style: italic
          weight: 300
